# Generated by Django 2.0.1 on 2018-09-10 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InstaVision', '0002_auto_20180909_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentsfile',
            name='file',
            field=models.TextField(),
        ),
    ]
